CREATE TABLE Admins (Admin_ID int(10) NOT NULL AUTO_INCREMENT, First_Name varchar(10) NOT NULL, Last_Name varchar(10) NOT NULL, Email varchar(50) NOT NULL UNIQUE, Access_Level varchar(10) NOT NULL, PRIMARY KEY (Admin_ID));
CREATE TABLE Authors (Author_ID int(10) NOT NULL AUTO_INCREMENT, First_Name varchar(10) NOT NULL, Last_Name varchar(10) NOT NULL, Biography varchar(1000), PRIMARY KEY (Author_ID));
CREATE TABLE Books (Book_ID int(10) NOT NULL AUTO_INCREMENT, Title varchar(100) NOT NULL, Author_ID int(10) NOT NULL, Genre_ID int(10) NOT NULL, ISBN varchar(13) NOT NULL, Publication_Year date NOT NULL, PRIMARY KEY (Book_ID));
CREATE TABLE Books_Authors (BooksBook_ID int(10) NOT NULL, AuthorsAuthor_ID int(10) NOT NULL, PRIMARY KEY (BooksBook_ID, AuthorsAuthor_ID));
CREATE TABLE Checkouts (Checkout_ID int(10) NOT NULL AUTO_INCREMENT, Member_ID int(10) NOT NULL, Copy_ID int(10) NOT NULL, Checkout_Date date NOT NULL, Due_Date date NOT NULL, Return_Date int(10) NOT NULL, Librarian_ID int(10) NOT NULL, PRIMARY KEY (Checkout_ID));
CREATE TABLE Copy (Copy_ID int(10) NOT NULL AUTO_INCREMENT, Book_ID int(10) NOT NULL, Availability_Status varchar(20) NOT NULL, PRIMARY KEY (Copy_ID));
CREATE TABLE Fines (Fine_ID int(10) NOT NULL AUTO_INCREMENT, Member_ID int(10) NOT NULL, Checkout_ID int(10) NOT NULL, Amount int(5) NOT NULL, Payment_Status varchar(50) NOT NULL, PRIMARY KEY (Fine_ID));
CREATE TABLE Genre (Genre_ID int(10) NOT NULL AUTO_INCREMENT, Genre_Name varchar(10) NOT NULL, PRIMARY KEY (Genre_ID));
CREATE TABLE Librarians (Librarian_ID int(10) NOT NULL AUTO_INCREMENT, First_Name varchar(10) NOT NULL, Last_Name varchar(10) NOT NULL, Email varchar(50) NOT NULL UNIQUE, PRIMARY KEY (Librarian_ID));
CREATE TABLE Members (Member_ID int(10) NOT NULL AUTO_INCREMENT, First_Name varchar(10) NOT NULL, Last_Name varchar(10) NOT NULL, Email varchar(50) NOT NULL UNIQUE, Subscription_ID int(10) NOT NULL, PRIMARY KEY (Member_ID));
CREATE TABLE Reservations (Reservation_ID int(10) NOT NULL AUTO_INCREMENT, Member_ID int(10) NOT NULL, Copy_ID int(10) NOT NULL, Reservation_Date date NOT NULL, CheckoutsCheckout_ID int(10) NOT NULL, PRIMARY KEY (Reservation_ID));
CREATE TABLE Reviews (Review_ID int(10) NOT NULL AUTO_INCREMENT, Member_ID int(10) NOT NULL, Book_ID int(10) NOT NULL, Review_Text varchar(1000), Ratings int(10), PRIMARY KEY (Review_ID));
CREATE TABLE Subscriptions (Subscription_ID int(10) NOT NULL AUTO_INCREMENT, Subscription_Type varchar(50) NOT NULL, Fee int(5) NOT NULL, Duration int(10) NOT NULL, PRIMARY KEY (Subscription_ID));
ALTER TABLE Fines ADD CONSTRAINT associated_with FOREIGN KEY (Checkout_ID) REFERENCES Checkouts (Checkout_ID);
ALTER TABLE Books_Authors ADD CONSTRAINT belong_to FOREIGN KEY (BooksBook_ID) REFERENCES Books (Book_ID);
ALTER TABLE Books ADD CONSTRAINT `belongs to` FOREIGN KEY (Genre_ID) REFERENCES Genre (Genre_ID);
ALTER TABLE Copy ADD CONSTRAINT `can have` FOREIGN KEY (Book_ID) REFERENCES Books (Book_ID);
ALTER TABLE Checkouts ADD CONSTRAINT can_be_checked_out FOREIGN KEY (Copy_ID) REFERENCES Copy (Copy_ID);
ALTER TABLE Reservations ADD CONSTRAINT can_be_reserved FOREIGN KEY (Copy_ID) REFERENCES Copy (Copy_ID);
ALTER TABLE Fines ADD CONSTRAINT can_get FOREIGN KEY (Member_ID) REFERENCES Members (Member_ID);
ALTER TABLE Reservations ADD CONSTRAINT can_make FOREIGN KEY (Member_ID) REFERENCES Members (Member_ID);
ALTER TABLE Checkouts ADD CONSTRAINT do FOREIGN KEY (Member_ID) REFERENCES Members (Member_ID);
ALTER TABLE Members ADD CONSTRAINT have FOREIGN KEY (Subscription_ID) REFERENCES Subscriptions (Subscription_ID);
ALTER TABLE Reviews ADD CONSTRAINT `may have` FOREIGN KEY (Book_ID) REFERENCES Books (Book_ID);
ALTER TABLE Checkouts ADD CONSTRAINT process_checkouts FOREIGN KEY (Librarian_ID) REFERENCES Librarians (Librarian_ID);
ALTER TABLE Books_Authors ADD CONSTRAINT writee FOREIGN KEY (AuthorsAuthor_ID) REFERENCES Authors (Author_ID);
ALTER TABLE Reviews ADD CONSTRAINT writes FOREIGN KEY (Member_ID) REFERENCES Members (Member_ID);
